# Generated by Django 2.0 on 2019-05-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePresencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarcompra', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('preciocompra', models.IntegerField()),
                ('cantidaddisponible', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes_Sandwiches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.Ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30)),
                ('fechaentrega', models.DateField()),
                ('clientepedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.ClientePedido')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=512)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sandwiches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=512)),
                ('vegetarianocarne', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwiches_ClientePresencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('clientepresencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.ClientePresencial')),
                ('sandwiches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.Sandwiches')),
            ],
        ),
        migrations.CreateModel(
            name='Sandwiches_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('entregado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.Pedido')),
                ('sandwiches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.Sandwiches')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientes_sandwiches',
            name='sandwiches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.Sandwiches'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olivo.Proveedores'),
        ),
    ]
