# Generated by Django 2.0 on 2019-05-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='cantidaddisponible',
            field=models.IntegerField(),
        ),
    ]
